In [10]:
import sys
print(sys.version)
import tensorflow as tf
import numpy as np
from mnist import MNIST
from matplotlib import pyplot as plt

3.8.6 (v3.8.6:db455296be, Sep 23 2020, 13:31:39) 
[Clang 6.0 (clang-600.0.57)]


In [36]:
def LeNet5_model():
    model = tf.keras.models.Sequential() 
    model.add(tf.keras.layers.Conv2D(8, 5, input_shape=(28, 28, 1), padding='same', activation='relu'))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))  
    model.add(tf.keras.layers.Conv2D(16, 3, activation='relu'))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))  
    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(120, activation='relu'))
    model.add(tf.keras.layers.Dense(64, activation='relu'))
    model.add(tf.keras.layers.Dense(10, activation='softmax'))# енто совт-арг-макс а не совт-макс, кажется
    return model

In [33]:
def CPCP_model():
    model = tf.keras.models.Sequential() 
    model.add(tf.keras.layers.Conv2D(32, 3, input_shape=(28, 28, 1), activation='relu'))  
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    model.add(tf.keras.layers.Conv2D(64, 3, activation='relu'))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    model.add(tf.keras.layers.Conv2D(128, 3, activation='relu'))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(64, activation='relu'))
    model.add(tf.keras.layers.Dense(10, activation='softmax'))# енто совт-арг-макс а не совт-макс, кажется
    return model

In [50]:
def vgg_model(dropout=0.2):
    model = tf.keras.models.Sequential() 
    model.add(tf.keras.layers.Conv2D(16, 3, input_shape=(28, 28, 1), padding='same', activation='relu'))  
    model.add(tf.keras.layers.Conv2D(16, 3, padding='same', activation='relu'))  
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    model.add(tf.keras.layers.Dropout(dropout))
    model.add(tf.keras.layers.Conv2D(32, 3, activation='relu'))
    model.add(tf.keras.layers.Conv2D(32, 3, activation='relu'))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    model.add(tf.keras.layers.Dropout(dropout))
    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(512, activation='relu'))
    model.add(tf.keras.layers.Dense(10, activation='softmax'))# енто совт-арг-макс а не совт-макс, кажется
    return model

In [70]:
def read_data(path):
    mnist_data = MNIST(path)
    mnist_train_images, mnist_train_labels = mnist_data.load_training()
    mnist_test_images, mnist_test_labels = mnist_data.load_testing()
    x_train = np.array(mnist_train_images)
    y_train = np.array(mnist_train_labels)
    x_test = np.array(mnist_test_images)
    y_test = np.array(mnist_test_labels)
    x_train, x_test = x_train / 255.0, x_test / 255.0
    x_train = tf.reshape(x_train, [60000, 28, 28, 1])
    x_test = tf.reshape(x_test, [10000, 28, 28, 1])
    return x_train, y_train, x_test, y_test

In [23]:
# preapare data
x_train, y_train, x_test, y_test = read_data('./data/mnist')

In [17]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 24, 24, 6)         156       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 12, 12, 6)         0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 10, 10, 16)        880       
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 5, 5, 16)          0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 1, 1, 1000)        401000    
_________________________________________________________________
flatten_2 (Flatten)          (None, 1000)              0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 1000)             

In [48]:
# Lenet5
model = LeNet5_model()
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, verbose=1)
error, accuracy = model.evaluate(x_test, y_test, verbose=0)
print("LeNet5", error, accuracy)

Epoch 1/5
1875/1875 [==============================] - 27s 14ms/step - loss: 0.3970 - accuracy: 0.8765
Epoch 2/5
1875/1875 [==============================] - 25s 14ms/step - loss: 0.0593 - accuracy: 0.9811
Epoch 3/5
1875/1875 [==============================] - 25s 14ms/step - loss: 0.0407 - accuracy: 0.9871
Epoch 4/5
1875/1875 [==============================] - 30s 16ms/step - loss: 0.0294 - accuracy: 0.9904
Epoch 5/5
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0254 - accuracy: 0.9916
LeNet5 0.03099902719259262 0.9891999959945679


In [42]:
model = CPCP_model()
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, verbose=1)
error, accuracy = model.evaluate(x_test, y_test, verbose=0)
print("CPCP", error, accuracy)

Epoch 1/5
1875/1875 [==============================] - 51s 27ms/step - loss: 0.4255 - accuracy: 0.8632
Epoch 2/5
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0695 - accuracy: 0.9771
Epoch 3/5
1875/1875 [==============================] - 58s 31ms/step - loss: 0.0437 - accuracy: 0.9870
Epoch 4/5
1875/1875 [==============================] - 60s 32ms/step - loss: 0.0333 - accuracy: 0.9892
Epoch 5/5
1875/1875 [==============================] - 55s 30ms/step - loss: 0.0230 - accuracy: 0.9928
CPCP 0.03847016021609306 0.9896000027656555


In [51]:
model = vgg_model()
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, verbose=1)
error, accuracy = model.evaluate(x_test, y_test, verbose=0)
print("vgg", error, accuracy)

Epoch 1/5
1875/1875 [==============================] - 92s 47ms/step - loss: 0.3125 - accuracy: 0.9015
Epoch 2/5
1875/1875 [==============================] - 82s 44ms/step - loss: 0.0567 - accuracy: 0.9826
Epoch 3/5
1875/1875 [==============================] - 102s 55ms/step - loss: 0.0403 - accuracy: 0.9875
Epoch 4/5
1875/1875 [==============================] - 115s 62ms/step - loss: 0.0300 - accuracy: 0.9906
Epoch 5/5
1875/1875 [==============================] - 110s 59ms/step - loss: 0.0232 - accuracy: 0.9927
vgg 0.020278984680771828 0.9940999746322632


In [63]:
# VGG the best
error, accuracy = model.evaluate(x_test, y_test, verbose=0)
print(accuracy, error)
k = 10
predicted = model.predict(x_test)
result = [0] * len(predicted) # result class
sim = np.zeros((k, k)) 
maxr = np.ones((k, k)) * -1
for j in range(len(predicted)):
    res = predicted[j] # 10
    for i in range(len(res)):
        if res[i] > res[result[j]]:
            result[j] = i
        if maxr[y_test[j], i] < res[i]:
            maxr[y_test[j], i] = res[i]
            sim[y_test[j], i] = j
cm = tf.math.confusion_matrix(y_test, result)
print("CM\n",cm)
print(sim)


0.9940999746322632 0.020278984680771828
CM
 tf.Tensor(
[[ 977    0    0    0    0    0    1    1    1    0]
 [   0 1134    1    0    0    0    0    0    0    0]
 [   1    0 1027    0    0    0    0    3    1    0]
 [   0    1    0 1007    0    1    0    0    1    0]
 [   0    0    0    0  974    0    0    1    1    6]
 [   1    0    0    6    0  883    1    0    0    1]
 [   3    3    0    0    3    1  947    0    1    0]
 [   0    3    0    0    0    1    0 1020    1    3]
 [   0    0    0    0    0    1    0    0  971    2]
 [   0    0    0    0    3    2    0    1    2 1001]], shape=(10, 10), dtype=int32)
[[  10. 6651. 8382. 1748. 6651. 1748. 1621. 6597. 6651. 6597.]
 [7928.   14. 2018. 2266. 6572. 1527. 6572. 6572. 9071. 6572.]
 [2462.  659.   47. 1459.  646. 7249.  646. 4176. 8094. 8094.]
 [7233. 4443. 2927.   30. 2109. 4740. 2280. 2109. 5955. 3475.]
 [1178. 9669. 2836. 9669.   56. 9615.  160. 9669. 3534. 2130.]
 [3558. 1737. 3778. 2035. 1737.   23. 9729. 1299. 3778. 5997.]
 [3422

In [71]:
# test on fashion_mnist
x_train, y_train, x_test, y_test = read_data('./data/fashion-mnist')
model = vgg_model()
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, verbose=1)
error, accuracy = model.evaluate(x_test, y_test, verbose=0)
print("vgg", error, accuracy)

Epoch 1/5
1875/1875 [==============================] - 71s 38ms/step - loss: 0.6582 - accuracy: 0.7600
Epoch 2/5
1875/1875 [==============================] - 72s 38ms/step - loss: 0.3230 - accuracy: 0.8813
Epoch 3/5
1875/1875 [==============================] - 81s 43ms/step - loss: 0.2631 - accuracy: 0.9039
Epoch 4/5
1875/1875 [==============================] - 77s 41ms/step - loss: 0.2363 - accuracy: 0.9124
Epoch 5/5
1875/1875 [==============================] - 75s 40ms/step - loss: 0.2125 - accuracy: 0.9210
vgg 0.2469007521867752 0.9126999974250793
